# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_home_layout(object):
    def setupUi(self, home_layout):
        home_layout.setObjectName("home_layout")
        home_layout.resize(1000, 700)
        self.centralwidget = QtWidgets.QWidget(home_layout)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 10, 951, 151))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btnDiemDanh = QtWidgets.QPushButton(self.centralwidget)
        self.btnDiemDanh.setGeometry(QtCore.QRect(280, 140, 461, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnDiemDanh.setFont(font)
        self.btnDiemDanh.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.btnDiemDanh.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.btnDiemDanh.setObjectName("btnDiemDanh")
        self.btnDuLieu = QtWidgets.QPushButton(self.centralwidget)
        self.btnDuLieu.setGeometry(QtCore.QRect(280, 250, 461, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnDuLieu.setFont(font)
        self.btnDuLieu.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.btnDuLieu.setObjectName("btnDuLieu")
        self.btnLopHoc = QtWidgets.QPushButton(self.centralwidget)
        self.btnLopHoc.setGeometry(QtCore.QRect(280, 350, 461, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnLopHoc.setFont(font)
        self.btnLopHoc.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.btnLopHoc.setObjectName("btnLopHoc")
        self.btnSinhVien = QtWidgets.QPushButton(self.centralwidget)
        self.btnSinhVien.setGeometry(QtCore.QRect(280, 450, 461, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnSinhVien.setFont(font)
        self.btnSinhVien.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.btnSinhVien.setObjectName("btnSinhVien")
        self.btnThoat = QtWidgets.QPushButton(self.centralwidget)
        self.btnThoat.setGeometry(QtCore.QRect(280, 550, 461, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnThoat.setFont(font)
        self.btnThoat.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.btnThoat.setObjectName("btnThoat")
        home_layout.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(home_layout)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menubar.setObjectName("menubar")
        home_layout.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(home_layout)
        self.statusbar.setObjectName("statusbar")
        home_layout.setStatusBar(self.statusbar)

        self.retranslateUi(home_layout)
        QtCore.QMetaObject.connectSlotsByName(home_layout)

    def retranslateUi(self, home_layout):
        _translate = QtCore.QCoreApplication.translate
        home_layout.setWindowTitle(_translate("home_layout", "MainWindow"))
        self.label.setText(_translate("home_layout", "HỆ THỐNG ĐIỂM DANH BẰNG NHẬN DIỆN GƯƠNG MẶT"))
        self.btnDiemDanh.setText(_translate("home_layout", "ĐIỂM DANH"))
        self.btnDuLieu.setText(_translate("home_layout", "DỮ LIỆU"))
        self.btnLopHoc.setText(_translate("home_layout", "QUẢN LÍ LỚP HỌC"))
        self.btnSinhVien.setText(_translate("home_layout", "QUẢN LÍ SINH VIÊN"))
        self.btnThoat.setText(_translate("home_layout", "THOÁT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    home_layout = QtWidgets.QMainWindow()
    ui = Ui_home_layout()
    ui.setupUi(home_layout)
    home_layout.show()
    sys.exit(app.exec_())
